Fix: Bug loading all feature flags to the user portal.
massenergize/api pull request #1106
Opened 2024-07-11 13:55 UTC by abdullai-t

####  Summary / Highlights
This pull request addresses a critical bug affecting the loading of feature flags into the user portal. With this fix, users wouldn't see features that are not open to their communities.

#### Details (Give details about what this PR accomplishes, include any screenshots etc)

https://github.com/massenergize/api/assets/42780120/b4b5821a-6c73-42cb-9f61-cf658c1b7557

#### Testing Steps (Provide details on how your changes can be tested)

#### Requirements (place an `x` in each `[ ]`)
* [ ] I've read and understood the [Contributing Guidelines](/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've tested my changes manually.
* [ ] I've added unit tests to my PR.

##### Transparency ([Project board](https://github.com/orgs/massenergize/projects/7/views/2))
* [ ] I've given my PR a meaningful title.
* [ ] I linked this PR to the relevant issue.
* [ ] I moved the linked issue from the "Sprint backlog" to "In progress" when I started this.
* [ ] I moved the linked issue to "QA Verification" now that it is ready to merge.

2024-07-11 14:17 UTC, frimpongopoku commented
@abdullai-t , what was the problem?

2024-07-11 16:04 UTC, abdullai-t commented
> @abdullai-t , what was the problem?

The filter function for getting the feature flags for a community where the audience is ALL_EXCEPT was flawed. As a result, all feature flags with the ALL_EXCEPT audience were returned, regardless of whether the community is allowed or not.

2024-07-11 17:10 UTC, Opoku-Agyemang requested changes
no tests?

2024-07-11 17:11 UTC, Opoku-Agyemang commented on src/api/store/community.py
> +                return get_enabled_flags(community), None
is there a corresponding FE change for this?  do they need to go in at the same time?

2024-07-13 02:10 UTC, Opoku-Agyemang approved these changes

2024-07-15 09:13 UTC, merged