Add support for managing supported languages
massenergize/api pull request #1123
Opened 2024-07-24 17:24 UTC by archx3

####  Summary / Highlights
Implemented CRUD operations for managing supported languages within the application. Added integration tests to ensure correct functionality and access control, confirming super admin permissions are required for creation.

#1084 
#### Details (Give details about what this PR accomplishes, include any screenshots etc)

#### Testing Steps (Provide details on how your changes can be tested)

#### Requirements (place an `x` in each `[ ]`)
* [x] I've read and understood the [Contributing Guidelines](/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've tested my changes manually.
* [ ] I've added unit tests to my PR.

##### Transparency ([Project board](https://github.com/orgs/massenergize/projects/7/views/2))
* [x] I've given my PR a meaningful title.
* [x] I linked this PR to the relevant issue.
* [x] I moved the linked issue from the "Sprint backlog" to "In progress" when I started this.
* [ ] I moved the linked issue to "QA Verification" now that it is ready to merge.

2024-07-25 08:50 UTC, Opoku-Agyemang requested changes
Nice work.  left some comments

2024-07-25 08:50 UTC, Opoku-Agyemang commented on src/api/handlers/supported_language.py
> +            return MassenergizeResponse(error="Please provide a valid language code")
small suggestion.  
```suggestion
              # some constants defined in some file
             INVALID_LANGUAGE_CODE_ERROR_MSG = "Please provide a valid language code"

            return MassenergizeResponse(error=INVALID_LANGUAGE_CODE_ERROR_MSG)
```

2024-07-25 08:50 UTC, Opoku-Agyemang commented on src/api/services/supported_language.py
> +            print(e)
remove print statements.  maybe you wanna log it instead?
log.exception(.....)

2024-07-25 08:50 UTC, Opoku-Agyemang commented on src/api/store/supported_language.py
> +                return None, CustomMassenergizeError("Please provide a valid id or code")
same feedback here.  centralize your error messages somewhere and reference them here.
Also its also good for this particular case that we log what that invalid code is.
```suggestion
                return None, CustomMassenergizeError("Please provide a valid id or code: {0}".format(language_code)
```

2024-07-25 08:50 UTC, Opoku-Agyemang commented on src/api/store/supported_language.py
> +            log(e)
stay consistent with the pattern we have.
log.exception.  It makes refactoring easier.

2024-07-25 17:10 UTC, archx3 commented
Changes done but test are still failing because models can't be found in this branch.
They'll pass when the models in [database-translatable-fields](https://github.com/massenergize/api/tree/database-translatable-fields) are merged

2024-07-26 06:34 UTC, Opoku-Agyemang requested changes

2024-07-26 06:34 UTC, Opoku-Agyemang commented on src/api/tests/integration/test_supported_languages.py
> +        print(response)
we still have print statements

2024-07-26 06:34 UTC, Opoku-Agyemang commented on src/api/services/supported_language.py
> +            return None, str(e)
also should we not be returning a proper error not a string as an error?

2024-07-26 06:34 UTC, Opoku-Agyemang commented on src/api/handlers/supported_language.py
> +            return MassenergizeResponse(error="Please provide a valid language code and name")
you can even define the error messages texts at the top of the file as constants.

2024-07-26 06:34 UTC, Opoku-Agyemang commented on src/database/migrations/0153_staticsitetext_supportedlanguage_texthash_and_more.py
> +# Generated by Django 4.2.1 on 2024-07-25 11:05
this file is already in the other PR https://github.com/massenergize/api/pull/1119/files
Maybe rebase?  since its now merged in

2024-08-03 15:12 UTC, Opoku-Agyemang approved these changes

2024-08-03 15:12 UTC, merged