Sam feature flags
massenergize/api pull request #531
Opened 2022-07-04 07:00 UTC by Opoku-Agyemang

####  Summary / Highlights

#### Details (Give details about what this PR accomplishes, include any screenshots etc)

#### Testing Steps (Provide details on how your changes can be tested)

#### Requirements (place an `x` in each `[ ]`)
* [ ] I've read and understood the [Contributing Guidelines](/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've tested my changes manually.
* [ ] I've added unit tests to my PR.

##### Transparency ([Project board](https://github.com/orgs/massenergize/projects/7/views/2))
* [ ] I've given my PR a meaningful title.
* [ ] I linked this PR to the relevant issue.
* [ ] I moved the linked issue from the "Sprint backlog" to "In progress" when I started this.
* [ ] I moved the linked issue to "QA Verification" now that it is ready to merge.

2022-07-05 06:49 UTC, Opoku-Agyemang commented on src/_main_/settings.py
> +RUN_CELERY_LOCALLY = True
will revert this before merging.  Have it here to prevent mistakenly migrating to dev as this PR requires migrations to test

2022-07-06 06:46 UTC, frimpongopoku commented
I have made another branch off this one. I am just adding tiny things. 
I want to make it cater for features that are available to everyone except a select list of communities as well 🤔. 
And also add a route to create the flags from the sadmin frontend.

I will make another PR when thats done, so should we wait and merge that one instead? 🤔

2022-07-07 06:29 UTC, frimpongopoku approved these changes
Works well, just adding adding a few things on. So  lets not merge yet

2022-07-13 09:36 UTC, frimpongopoku commented
@BradHN1  @Opoku-Agyemang @Davidjwkinghorn @abdullai-t, made a few tweaks 💀

2022-07-18 08:17 UTC, Opoku-Agyemang commented on src/api/handlers/feature_flag.py
> +    @admins_only
```suggestion
    @super_admins_only
```

2022-07-18 08:17 UTC, Opoku-Agyemang commented on src/database/models.py
> +    users = models.ManyToManyField(UserProfile, blank=True, related_name="user_feature_flags")
the related names should be consistent.

2022-07-18 08:17 UTC, Opoku-Agyemang commented on src/_main_/utils/feature_flags/FeatureFlagConstants.py
> +class FeatureFlagCostants:
```suggestion
class FeatureFlagConstants:
```

2022-07-19 11:21 UTC, frimpongopoku commented
@Opoku-Agyemang @BradHN1 @Davidjwkinghorn I have added the tests, and implemented @Opoku-Agyemang 's feedback. I think we are ready here 🤔

2022-08-04 18:51 UTC, BradHN1 commented on src/api/handlers/feature_flag.py
> +        self.add("/featureFlags.listForSuperAdmins", self.list_feature_flags_for_super_admins)
change to listForSuperAdmin   (consistent with other routes)

2022-08-04 18:57 UTC, BradHN1 commented on src/database/models.py
> +    """
please add some comments on the attributes.  What is owner, audience, user_audience, etc.
The migration file in the PR doesn't reflect this version of the model.

2022-08-04 19:05 UTC, BradHN1 commented on src/database/models.py
> +    expires_on = models.DateTimeField(null=True, blank=True)
Null or blank should mean the feature never expires

2022-08-04 19:20 UTC, BradHN1 requested changes
Minor changes requested

2022-08-09 14:56 UTC, merged