Tags to media library
massenergize/api pull request #585
Opened 2022-09-16 04:53 UTC by frimpongopoku

Works with frontend PR: https://github.com/massenergize/frontend-admin/pull/718 

- [ ] Changes to allow admins to add tags to images when they upload 
- [ ] Changes to allow admins to include tags as a search criteria 
- [ ] Pulled in all the changes in [this PR](https://github.com/massenergize/api/pull/551) as well.

2022-09-20 02:24 UTC, Opoku-Agyemang commented on src/api/services/media_library.py
> +            "information": user_info,
i think user_info is more explicit.  information is very generic.  You can also go for `user_information`

2022-09-20 02:26 UTC, Opoku-Agyemang requested changes
i think the tests are breaking.  Can you add tests for this new functionality and also make sure the other tests are not breaking?

2022-10-05 20:33 UTC, Davidjwkinghorn commented
I think I'm ready to merge this in, but I'm not seeing the filters for the tags anywhere when I run this with the admin portal changes. @frimpongopoku do you know why that might be?

2022-10-11 14:52 UTC, Davidjwkinghorn commented
I'm going to try merging this, in case it's just something weird with my local environment.

2022-10-11 14:52 UTC, merged